version: "3.9"

services:
  whatsmeow-adapter:
    build: .
    image: ghcr.io/mbap-dev/provider-whatsmeow:latest
    restart: unless-stopped
    environment:
      # Ex.: amqp://user:pass@rb-host:5672/vhost
      AMQP_URL: "${AMQP_URL}"
      AMQP_EXCHANGE: "${AMQP_EXCHANGE:-unoapi.outgoing}"
      AMQP_BINDING: "${AMQP_BINDING:-provider.whatsmeow.*}"
      AMQP_QUEUE: "${AMQP_QUEUE:-provider.whatsmeow}"
      WEBHOOK_BASE: "${WEBHOOK_BASE:-}"       # opcional
      SESSION_STORE: "/var/lib/whatsmeow"
      HTTP_ADDR: ":8080"
      S3_ENDPOINT: "${S3_ENDPOINT:-}"
      S3_REGION: "${S3_REGION:-}"
      S3_ACCESS_KEY: "${S3_ACCESS_KEY:-}"
      S3_SECRET_KEY: "${S3_SECRET_KEY:-}"
      S3_BUCKET: "${S3_BUCKET:-}"
      S3_USE_SSL: "${S3_USE_SSL:-false}"
    volumes:
      - ./data/whatsmeow:/var/lib/whatsmeow
    ports:
      - "8080:8080"
